FROM node:20-alpine AS builder
WORKDIR /agrigrowapp

RUN apk add --no-cache git
RUN git clone https://github.com/jyotsnatalasila/agrigrow-docker.git .

RUN npm ci --legacy-peer-deps
RUN npm run build

FROM nginx:alpine
RUN rm -rf /usr/share/nginx/html/*
COPY --from=builder /agrigrowapp/build/ /usr/share/nginx/html/
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 4000
CMD ["nginx", "-g", "daemon off;"]